name: Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: gradle build --b ./Backend/build.gradle --info --continue

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Unit test report 1
        path: /home/runner/work/Poker/Poker/Backend/build/*-test-results/TEST-*.xml
        reporter: jest-junit        
    
    - name: Unit test report 2
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v2.4.4
      with:
        report_paths: /home/runner/work/Poker/Poker/Backend/build/*-test-results/TEST-*.xml
