name: Backend CI

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: gradle build --b ./Backend/build.gradle --info --continue

    - name: Unit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Unit test reports
        path: /home/runner/work/Poker/Poker/Backend/build/unit-test-results/TEST-*.xml
        reporter: java-junit
        
    - name: Integration Test Report
      uses: dorny/test-reporter@v1
      if: ${{ hashFiles('**/integration-test-results/TEST-*.xml') != '' }}
      with:
        name: Integration test reports
        path: /home/runner/work/Poker/Poker/Backend/build/integration-test-results/TEST-*.xml
        reporter: java-junit
