name: Backend CI

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: gradle build --b ./Backend/build.gradle --info --continue
    - name: JUnit Report Action
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v2.4.4
      with:
        report_paths: /home/runner/work/Poker/Poker/Backend/build/test-junit-xml/testresult.xml/TEST-*.xml
