name: Backend CI

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'
  workflow_dispatch:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: gradle build --b ./Backend/build.gradle --continue

    - name: Unit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Backend Unit test reports
        path: /home/runner/work/Poker/Poker/Backend/build/unit-test-results/TEST-*.xml
        reporter: java-junit
        
    - name: Integration Test Report
      uses: dorny/test-reporter@v1
      if: ${{ hashFiles('**/integration-test-results/TEST-*.xml') != '' }}
      with:
        name: Backend Integration test reports
        path: /home/runner/work/Poker/Poker/Backend/build/integration-test-results/TEST-*.xml
        reporter: java-junit
        
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: Backend/build/customJacocoReportDir/test/jacocoTestReport.csv
        intervals: 80 70 60 50 40 0

    - name: Add coverage to PR
      id: jacoco
      continue-on-error: true
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: /home/runner/work/Poker/Poker/Backend/build/customJacocoReportDir/test/jacocoTestReport.xml
        token: ${{ secrets.CODE_COV_SECRET }}
        min-coverage-overall: 40
        title: JaCoCo code coverage

    - name: Commit coverage badge (if changed)
      run: |
        git checkout @ -- Backend/resources/poker.db
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'bognargabor99'
          git config --global user.email '61208246@users.noreply.github.com'
          git add .github/badges
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi
