name: Backend CI

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'
  workflow_dispatch:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: gradle build --b ./Backend/build.gradle --info --continue

    - name: Unit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Unit test reports
        path: /home/runner/work/Poker/Poker/Backend/build/unit-test-results/TEST-*.xml
        reporter: java-junit
        
    - name: Integration Test Report
      uses: dorny/test-reporter@v1
      if: ${{ hashFiles('**/integration-test-results/TEST-*.xml') != '' }}
      with:
        name: Integration test reports
        path: /home/runner/work/Poker/Poker/Backend/build/integration-test-results/TEST-*.xml
        reporter: java-junit
        
    - name: Code coverage report
      uses: codecov/codecov-action@v2
      with:
        files: /home/runner/work/Poker/Poker/Backend/build/customJacocoReportDir/test/jacocoTestReport.xml
        name: Code coverage report # optional
        verbose: true # optional (default = false)
        dry_run: true
        
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        path: ${{ github.workspace }}/build/customJacocoReportDir/test/jacocoTestReport.xml
        token: ${{ secrets.CODE_COV_SECRET }}
        min-coverage-overall: 40
        title: JaCoCo code coverage
