name: Backend CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
    
    - uses: eskatos/gradle-command-action@v1
      with:
          arguments: test --info
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
