name: Backend CI

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: gradle build --b ./Backend/build.gradle --info --continue

    - name: Unit test report
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v2.4.4
      with:
        report_paths: /home/runner/work/Poker/Poker/Backend/build/unit-test-results/TEST-*.xml

    - name: Integration test report
      if: ${{ hashFiles('integration-test-results/TEST-*.xml') != '' }}
      uses: mikepenz/action-junit-report@v2.4.4
      with:
        report_paths: /home/runner/work/Poker/Poker/Backend/build/integration-test-results/TEST-*.xml
