name: Frontend CI

on:
  push:
    paths:
      - 'Frontend/**'
  pull_request:
    paths:
      - 'Frontend/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: gradle build --b ./Frontend/build.gradle --continue
      
    - name: Unit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Frontend Unit test reports
        path: /home/runner/work/Poker/Poker/Frontend/app/build/test-results/test*UnitTest/TEST-*.xml
        reporter: java-junit
