name: Frontend CI

on:
  push:
    paths:
      - 'Frontend/**'
  pull_request:
    paths:
      - 'Frontend/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: gradle build --b ./Frontend/build.gradle --continue
